# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import model_utils.fields
import uuid
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, verbose_name='created', editable=False)),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, verbose_name='modified', editable=False)),
                ('romanized_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('released', models.DateField(db_index=True, null=True, blank=True)),
                ('price', models.IntegerField(null=True, blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('released_as', models.CharField(help_text='Used for temporary name changes (i.e., \xe3\x82\x80\xe3\x81\xa6\xe3\x82\x93\xe5\xa8\x98\xe3\x80\x82).', max_length=200, blank=True)),
                ('romanized_released_as', models.CharField(help_text='Used for temporary name changes (i.e., Muten Musume).', max_length=200, blank=True)),
                ('number', models.CharField(max_length=10, blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('is_indie', models.BooleanField(default=False, verbose_name='indie release?')),
                ('note', models.TextField(blank=True)),
                ('art', models.ImageField(null=True, upload_to='merchandise/music/editions/', blank=True)),
                ('is_compilation', models.BooleanField(default=False, verbose_name='compilation?')),
                ('edited_by', models.ManyToManyField(related_name='albums_edits', null=True, to='accounts.Editor', blank=True)),
                ('groups', models.ManyToManyField(related_name='albums', null=True, to='people.Group', blank=True)),
                ('idols', models.ManyToManyField(related_name='albums', null=True, to='people.Idol', blank=True)),
            ],
            options={
                'ordering': ('-released',),
                'abstract': False,
                'get_latest_by': 'released',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('romanized_name', models.CharField(max_length=100, blank=True)),
                ('name', models.CharField(max_length=100, blank=True)),
                ('kind', models.IntegerField(default=1, db_index=True, choices=[(1, 'Regular'), (2, 'Limited'), (3, 'Single V'), (4, 'Event V'), (11, 'Commemorative'), (12, 'Digital'), (99, 'Other')])),
                ('released', models.DateField(db_index=True, null=True, blank=True)),
                ('catalog_number', models.CharField(max_length=100, blank=True)),
                ('price', models.IntegerField(null=True, blank=True)),
                ('art', models.ImageField(null=True, upload_to='merchandise/music/editions/', blank=True)),
                ('album', models.ForeignKey(on_delete=models.SET_NULL, related_name='editions', blank=True, to='music.Album', null=True)),
            ],
            options={
                'ordering': ('kind', 'romanized_name'),
                'get_latest_by': 'released',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('romanized_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='merchandise/music/labels/', blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, verbose_name='created', editable=False)),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, verbose_name='modified', editable=False)),
                ('romanized_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('released', models.DateField(db_index=True, null=True, blank=True)),
                ('price', models.IntegerField(null=True, blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('released_as', models.CharField(help_text='Used for temporary name changes (i.e., \xe3\x82\x80\xe3\x81\xa6\xe3\x82\x93\xe5\xa8\x98\xe3\x80\x82).', max_length=200, blank=True)),
                ('romanized_released_as', models.CharField(help_text='Used for temporary name changes (i.e., Muten Musume).', max_length=200, blank=True)),
                ('number', models.CharField(max_length=10, blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('is_indie', models.BooleanField(default=False, verbose_name='indie release?')),
                ('note', models.TextField(blank=True)),
                ('art', models.ImageField(null=True, upload_to='merchandise/music/editions/', blank=True)),
                ('has_8cm', models.BooleanField(default=False, verbose_name='8cm version?')),
                ('has_lp', models.BooleanField(default=False, verbose_name='LP version?')),
                ('has_cassette', models.BooleanField(default=False, verbose_name='cassette version?')),
                ('edited_by', models.ManyToManyField(related_name='singles_edits', null=True, to='accounts.Editor', blank=True)),
                ('groups', models.ManyToManyField(related_name='singles', null=True, to='people.Group', blank=True)),
                ('idols', models.ManyToManyField(related_name='singles', null=True, to='people.Idol', blank=True)),
                ('label', models.ForeignKey(on_delete=models.SET_NULL, related_name='singles', blank=True, to='music.Label', null=True)),
                ('participating_groups', models.ManyToManyField(related_name='singles_attributed_to', null=True, to='people.Group', blank=True)),
                ('participating_idols', models.ManyToManyField(help_text='The remaining idols that are not a member of the given groups.', related_name='singles_attributed_to', null=True, to='people.Idol', blank=True)),
                ('submitted_by', models.ForeignKey(on_delete=models.SET_NULL, related_name='single_submissions', blank=True, to='accounts.Editor', null=True)),
            ],
            options={
                'ordering': ('-released',),
                'abstract': False,
                'get_latest_by': 'released',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('released_as', models.CharField(help_text='Used for temporary name changes (i.e., \xe3\x82\x80\xe3\x81\xa6\xe3\x82\x93\xe5\xa8\x98\xe3\x80\x82).', max_length=200, blank=True)),
                ('romanized_released_as', models.CharField(help_text='Used for temporary name changes (i.e., Muten Musume).', max_length=200, blank=True)),
                ('romanized_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, blank=True)),
                ('translated_name', models.CharField(max_length=200, blank=True)),
                ('is_cover', models.BooleanField(default=False, verbose_name='cover?')),
                ('is_alternate', models.BooleanField(default=False, verbose_name='alternate?')),
                ('romanized_name_alternate', models.CharField(max_length=200, verbose_name='alternate name (romanized)', blank=True)),
                ('name_alternate', models.CharField(max_length=200, verbose_name='alternate name', blank=True)),
                ('lyrics', models.TextField(help_text='Remember to use two spaces at the end of a line for line breaks!', blank=True)),
                ('romanized_lyrics', models.TextField(blank=True)),
                ('translated_lyrics', models.TextField(blank=True)),
                ('translation_notes', models.TextField(blank=True)),
                ('processed_lyrics', models.TextField(editable=False, blank=True)),
                ('processed_romanized_lyrics', models.TextField(editable=False, blank=True)),
                ('processed_translated_lyrics', models.TextField(editable=False, blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slug', models.SlugField(max_length=200, blank=True)),
                ('album', models.ForeignKey(on_delete=models.SET_NULL, related_name='tracks', blank=True, to='music.Album', null=True)),
                ('arrangers', models.ManyToManyField(related_name='arranged', null=True, to='people.Staff', blank=True)),
                ('composers', models.ManyToManyField(related_name='composed', null=True, to='people.Staff', blank=True)),
                ('groups', models.ManyToManyField(related_name='tracks', null=True, to='people.Group', blank=True)),
                ('idols', models.ManyToManyField(related_name='tracks', null=True, to='people.Idol', blank=True)),
                ('lyricists', models.ManyToManyField(related_name='wrote', null=True, to='people.Staff', blank=True)),
                ('original_track', models.ForeignKey(on_delete=models.SET_NULL, related_name='children', blank=True, to='music.Track', help_text=b"If this track is a cover or alternate, choose the original track it's based off of.", null=True)),
                ('participating_groups', models.ManyToManyField(related_name='tracks_attributed_to', null=True, to='people.Group', blank=True)),
                ('participating_idols', models.ManyToManyField(help_text='The remaining idols that are not a member of the given groups.', related_name='tracks_attributed_to', null=True, to='people.Idol', blank=True)),
                ('single', models.ForeignKey(on_delete=models.SET_NULL, related_name='tracks', blank=True, to='music.Single', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TrackOrder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('disc', models.PositiveSmallIntegerField(default=1)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('is_aside', models.BooleanField(default=False, verbose_name='a-side?')),
                ('is_bside', models.BooleanField(default=False, verbose_name='b-side?')),
                ('is_album_only', models.BooleanField(default=False, verbose_name='album only?')),
                ('is_instrumental', models.BooleanField(default=False, verbose_name='instrumental?')),
                ('edition', models.ForeignKey(on_delete=models.SET_NULL, related_name='order', to='music.Edition')),
                ('track', models.ForeignKey(on_delete=models.SET_NULL, related_name='appears_on', to='music.Track')),
            ],
            options={
                'ordering': ('disc', 'position'),
                'verbose_name': 'track',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('romanized_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, blank=True)),
                ('kind', models.PositiveSmallIntegerField(default=1, choices=[(1, 'Regular'), (2, 'Dance Shot'), (3, 'Close-up'), (4, 'Another'), (9, 'Other (PV)'), (11, 'Solo'), (12, 'Close-up (Solo)'), (21, 'Making of'), (22, 'Jacket Making'), (23, 'PV Making'), (31, 'Backstage'), (32, 'Performance'), (99, 'Other')])),
                ('released', models.DateField(null=True, blank=True)),
                ('still', models.ImageField(null=True, upload_to='merchandise/music/videos/', blank=True)),
                ('video_url', models.URLField(verbose_name='video URL', blank=True)),
                ('album', models.ForeignKey(on_delete=models.SET_NULL, related_name='videos', blank=True, to='music.Album', null=True)),
                ('single', models.ForeignKey(on_delete=models.SET_NULL, related_name='videos', blank=True, to='music.Single', null=True)),
            ],
            options={
                'get_latest_by': 'released',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VideoTrackOrder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('edition', models.ForeignKey(on_delete=models.SET_NULL, related_name='video_order', to='music.Edition')),
                ('video', models.ForeignKey(on_delete=models.SET_NULL, related_name='on_edition', to='music.Video')),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'video track',
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name='videotrackorder',
            unique_together=set([('edition', 'video')]),
        ),
        migrations.AddField(
            model_name='edition',
            name='single',
            field=models.ForeignKey(on_delete=models.SET_NULL, related_name='editions', blank=True, to='music.Single', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='edition',
            name='tracks',
            field=models.ManyToManyField(related_name='editions', null=True, through='music.TrackOrder', to='music.Track', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='edition',
            name='videos',
            field=models.ManyToManyField(related_name='editions', null=True, through='music.VideoTrackOrder', to='music.Video', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.ForeignKey(on_delete=models.SET_NULL, related_name='albums', blank=True, to='music.Label', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='album',
            name='participating_groups',
            field=models.ManyToManyField(related_name='albums_attributed_to', null=True, to='people.Group', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='album',
            name='participating_idols',
            field=models.ManyToManyField(help_text='The remaining idols that are not a member of the given groups.', related_name='albums_attributed_to', null=True, to='people.Idol', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='album',
            name='submitted_by',
            field=models.ForeignKey(on_delete=models.SET_NULL, related_name='album_submissions', blank=True, to='accounts.Editor', null=True),
            preserve_default=True,
        ),
    ]
